"""Change Donation model: delete - description, add - comment. Add default value in parameter 'create_date' in BaseModel

Revision ID: 4c63e102b60d
Revises: e987ed44ba18
Create Date: 2023-11-12 20:12:26.849407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c63e102b60d'
down_revision = 'e987ed44ba18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=True))
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.TEXT(), nullable=True))
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
