"""Add default value in parameter 'create_date' in BaseModel

Revision ID: f9b0a8aa75d4
Revises: 4c63e102b60d
Create Date: 2023-11-12 20:13:33.640118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9b0a8aa75d4'
down_revision = '4c63e102b60d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
